prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/base.yml
    path: styles/base.yml
  - url: https://raw.githubusercontent.com/ManageIQ/manageiq-style/master/styles/cc_base.yml
    path: styles/cc_base.yml
plugins:
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: rubocop-1-56-3
version: '2'
checks:
  complexity-logic:
    config:
      threshold: 10
  method-count:
    enabled: false
  method-lines:
    enabled: false
  file-lines:
    enabled: false
